[package]
name = "bomb_panic"
edition = "2024.beta"


[dependencies]
MoveStdlib = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "main", override = true }
One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "main" }

[addresses]
games = "0x0"
